"""The map page: built output stays out of git, Python never reaches the sources, and the
fetch registry's FEATURES block and mechanism modules hold their shape.

Read off the filesystem, the index and the sources, with no Node executed. The reasons are in
docs/DEVELOPING.md, "Architecture rules".
"""

from __future__ import annotations

import ast
import posixpath
import re
import subprocess
from pathlib import Path

import pytest

from tests.support.import_graph import (
    PKG,
    REPO,
    WEB,
    docstring_ids,
    module_name,
    package_of,
    parse,
    sources,
    targets,
)

FRONTEND = WEB / "frontend"
BUILT = WEB / "static"
FRONTEND_SRC = FRONTEND / "src"
FRONTEND_MAIN_TS = FRONTEND_SRC / "main.ts"
FRONTEND_REGISTRY_TS = FRONTEND_SRC / "app" / "registry.ts"
FRONTEND_PALETTE_TS = FRONTEND_SRC / "map" / "palette.ts"
FRONTEND_TILES_TS = FRONTEND_SRC / "map" / "tiles.ts"
REGISTRY_PY = PKG / "domain" / "maps" / "registry.py"

#: The banner ``vite.config.ts`` stamps into every file it emits.
BUILD_MARKER = "GENERATED by Vite"

#: Every file the build writes, and the whole of ``static/`` once a build has run.
BUILT_FILES: tuple[str, ...] = ("index.html", "app.js", "app.css", "vendor/LEAFLET-LICENSE")

#: Leaflet's licence, copied verbatim: a banner in it would modify the notice it reproduces.
COPIED_VERBATIM = "vendor/LEAFLET-LICENSE"

#: The root ``.gitignore`` line that keeps the build output out of the tree, verbatim.
STATIC_IGNORE_LINE = "src/satisfactory_mcp/interfaces/web/static/"

#: The mechanism side of the page: modules that hold a list and run it, and know none of the
#: features in it.
FRONTEND_MECHANISM = (
    FRONTEND_SRC / "app" / "load.ts",
    FRONTEND_SRC / "app" / "registry.ts",
    FRONTEND_SRC / "map" / "layers.ts",
    FRONTEND_SRC / "map" / "layercontrol" / "control.ts",
    FRONTEND_SRC / "map" / "layercontrol" / "radio-section.ts",
    FRONTEND_SRC / "map" / "layercontrol" / "mode-picker.ts",
    FRONTEND_SRC / "map" / "layercontrol" / "floor-picker.ts",
    FRONTEND_SRC / "map" / "palette.ts",
)

#: A CSS hex colour of any length, in code or comment.
HEX_COLOUR = re.compile(r"#[0-9a-fA-F]{3,8}\b")

#: A fetch registration: a call at module scope, anchored on the margin.
REGISTER_CALL = re.compile(r"^registerFetch[<(]", re.MULTILINE)

#: A bare side-effect import of a page module; stylesheets carry a dot and do not match.
_RELATIVE = r"((?:\./|(?:\.\./)+)[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*)"
BARE_IMPORT = re.compile(rf'^import "{_RELATIVE}";$', re.MULTILINE)

#: The tail of any other import of a page module, which may span lines.
FROM_IMPORT = re.compile(rf'from "{_RELATIVE}"')


def _names_in_code(path: Path, needle: str) -> bool:
    """Whether ``needle`` appears in a string value or import target of this module.

    Comments and docstrings are skipped, so a module may explain the rule it obeys.
    """
    tree = parse(path)
    prose = docstring_ids(tree)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if any(needle in target for target in targets(node, package_of(path))):
                return True
            continue
        if not isinstance(node, ast.Constant) or not isinstance(node.value, str):
            continue
        if id(node) not in prose and needle in node.value:
            return True
    return False


def _module_key(path: Path) -> str:
    """A page module's name for these rules: its path under ``src/``, without ``.ts``."""
    relative = path.relative_to(FRONTEND_SRC).as_posix()
    return relative.removesuffix(".ts").removesuffix(".d")


def _resolve_specifiers(importer: Path, specifiers: list[str]) -> set[str]:
    folder = posixpath.dirname(_module_key(importer))
    return {posixpath.normpath(posixpath.join(folder, specifier)) for specifier in specifiers}


def _ts_imports(path: Path) -> set[str]:
    """Every page module a ``.ts`` file imports -- bare, named, value or type."""
    text = path.read_text(encoding="utf-8")
    return _resolve_specifiers(path, BARE_IMPORT.findall(text) + FROM_IMPORT.findall(text))


def _page_modules() -> list[Path]:
    return sorted(FRONTEND_SRC.rglob("*.ts"))


def _registering_modules() -> set[str]:
    return {
        _module_key(path)
        for path in _page_modules()
        if REGISTER_CALL.search(path.read_text(encoding="utf-8"))
    }


def _ts_importers_of(module: str) -> set[str]:
    return {
        _module_key(path)
        for path in _page_modules()
        if _module_key(path) != module and module in _ts_imports(path)
    }


def test_the_built_page_stays_out_of_git():
    ignore = (REPO / ".gitignore").read_text(encoding="utf-8").splitlines()
    assert STATIC_IGNORE_LINE in ignore, (
        f".gitignore no longer carries `{STATIC_IGNORE_LINE}` -- the built page (which "
        "embeds minified Leaflet) must never be committed; a clone builds its own"
    )
    try:
        tracked = subprocess.run(
            ["git", "ls-files", "--", "src/satisfactory_mcp/interfaces/web/static"],
            cwd=REPO,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    except (FileNotFoundError, subprocess.CalledProcessError):
        pytest.skip("not a git checkout, or no git on PATH -- nothing to be tracked in")
    assert not tracked, (
        "build output is tracked in git again -- `git rm -r --cached` it; static/ is "
        "generated by `npm run build` and holds a dependency's compiled code:\n"
        + "\n".join(f"  {name}" for name in tracked)
    )


def test_the_served_page_is_build_output_and_nothing_else():
    if not BUILT.is_dir():
        pytest.skip("static/ has not been built here -- untracked output, absent on a clone")

    missing = [name for name in BUILT_FILES if not (BUILT / name).is_file()]
    assert not missing, (
        "the built bundle is incomplete -- run `npm ci && npm run build` in "
        f"{FRONTEND.name}/:\n" + "\n".join(f"  static/{name}" for name in missing)
    )
    unmarked = [
        name
        for name in BUILT_FILES
        if name != COPIED_VERBATIM
        and BUILD_MARKER not in (BUILT / name).read_text(encoding="utf-8")[:400]
    ]
    assert not unmarked, (
        "these served files carry no build banner, so they were either hand-edited or "
        "written by something that is not the build -- the source is "
        f"{FRONTEND.name}/src:\n" + "\n".join(f"  static/{name}" for name in unmarked)
    )
    strays = {
        str(path.relative_to(BUILT)).replace("\\", "/")
        for path in BUILT.rglob("*")
        if path.is_file()
    } - set(BUILT_FILES)
    assert not strays, (
        "static/ is build output and holds nothing else -- put the source in "
        f"{FRONTEND.name}/ and let the build emit it, or add it to BUILT_FILES with a "
        "reason:\n" + "\n".join(f"  static/{name}" for name in sorted(strays))
    )


def test_the_frontend_sources_are_not_reachable_from_python():
    """``app.py`` may name ``frontend/`` once: in the not-built instruction it serves at ``/``."""
    allowed = WEB / "app.py"
    tree = parse(allowed)
    prose = docstring_ids(tree)
    naming = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and id(node) not in prose
        and "frontend" in node.value
    ]
    assert len(naming) == 1 and "npm ci && npm run build" in naming[0].value, (
        "app.py may name frontend/ exactly once, in the not-built instruction served at / "
        "-- anything more is the server reaching past the built directory"
    )
    named = sorted(
        module_name(path)
        for path in sources(PKG)
        if path != allowed and _names_in_code(path, "frontend")
    )
    assert not named, (
        "these modules name the frontend sources in code -- the server serves the BUILT "
        "directory and nothing reaches past it:\n" + "\n".join(f"  {name}" for name in named)
    )
    assert not sources(FRONTEND), (
        "the npm project has grown Python -- it is a TypeScript build, and a .py file in "
        "it is either in the wrong tree or a build step that belongs in package.json:\n"
        + "\n".join(f"  {path}" for path in sources(FRONTEND))
    )


def test_the_page_and_the_registry_agree_on_the_old_base_map_names():
    """Old ``#mode=`` links keep working only while both sides keep the same three names."""
    legacy = next(
        [k.value for k in node.value.keys if isinstance(k, ast.Constant)]
        for node in ast.walk(parse(REGISTRY_PY))
        if isinstance(node, ast.Assign)
        and any(isinstance(t, ast.Name) and t.id == "LEGACY" for t in node.targets)
        and isinstance(node.value, ast.Dict)
    )
    tiles = FRONTEND_TILES_TS.read_text(encoding="utf-8")
    artwork = re.search(r'var ARTWORK = "([^"]+)";', tiles)
    assert artwork, "tiles.ts no longer names the artwork's registry id"
    assert artwork.group(1) == legacy[0], (artwork.group(1), legacy)
    assert re.search(r"var ALIASES[^=]*= \{ artwork: ARTWORK \}", tiles), (
        "the artwork alias is gone"
    )
    offered = re.findall(r'legacy\((ARTWORK|"[a-z]+")', tiles)
    names = [legacy[0] if name == "ARTWORK" else name.strip('"') for name in offered]
    assert names == legacy, (
        f"tiles.ts offers {names} before the registry answers; it serves {legacy}"
    )


def test_every_module_that_fetches_is_named_in_the_features_block():
    listed = _resolve_specifiers(
        FRONTEND_MAIN_TS, BARE_IMPORT.findall(FRONTEND_MAIN_TS.read_text(encoding="utf-8"))
    )
    registering = _registering_modules()
    assert registering, (
        "nothing calls registerFetch at module scope any more -- if the registry is gone, "
        "this rule and its section in docs/DEVELOPING.md should go with it"
    )
    missing = sorted(registering - listed)
    assert not missing, (
        "these modules register a fetch and nothing imports them for it -- add a bare "
        '`import "./path/name";` to the FEATURES block in main.ts, or their layers are dropped '
        "from the bundle with no error anywhere:\n" + "\n".join(f"  src/{n}.ts" for n in missing)
    )
    stale = sorted(listed - registering)
    assert not stale, (
        "these are imported for their side effect in main.ts's FEATURES block but register "
        "no fetch -- either they lost their registerFetch call (and their layer with it) "
        "or the line belongs somewhere the reason for it is visible:\n"
        + "\n".join(f"  src/{n}.ts" for n in stale)
    )


def test_the_mechanism_imports_no_module_that_fetches():
    registering = _registering_modules()
    for path in FRONTEND_MECHANISM:
        reached = sorted(_ts_imports(path) & registering)
        assert not reached, (
            f"src/{_module_key(path)}.ts imports a module that registers a fetch, which is "
            "what the registry exists to stop -- the feature declares what it wants fetched "
            "and this side runs the list:\n" + "\n".join(f"  -> src/{n}.ts" for n in reached)
        )


def test_no_mechanism_module_imports_a_module_that_imports_it():
    for path in FRONTEND_MECHANISM:
        reached = sorted(_ts_imports(path) & _ts_importers_of(_module_key(path)))
        assert not reached, (
            f"src/{_module_key(path)}.ts imports a module that imports it back, which is a "
            "ring: this side is a mechanism every feature reaches, so whatever it reaches "
            "would be evaluated before all of them:\n"
            + "\n".join(f"  -> src/{n}.ts" for n in reached)
        )
    values = [
        line
        for line in FRONTEND_REGISTRY_TS.read_text(encoding="utf-8").splitlines()
        if line.startswith("import ") and not line.startswith("import type ")
    ]
    assert not values, (
        "registry.ts imports something at runtime -- everything that draws imports it, so "
        "whatever this is would be evaluated before all of them:\n" + "\n".join(values)
    )


def test_no_colour_value_lives_in_palette_ts():
    text = FRONTEND_PALETTE_TS.read_text(encoding="utf-8")
    found = [
        f"  line {n}: {hit.group(0)}  in  {line.strip()[:88]}"
        for n, line in enumerate(text.splitlines(), start=1)
        for hit in [HEX_COLOUR.search(line)]
        if hit
    ]
    assert not found, (
        "palette.ts holds a colour value. It holds the comparison; the values belong to the "
        "module that draws with them, declared through declareColours so the dE audit can "
        "see them -- a hex here is a colour with no owner and no warrant:\n" + "\n".join(found)
    )


def test_the_page_frame_matches_geo():
    """``map.ts`` spells the map square as a literal; it must equal ``geo.MAP_SQUARE_M``."""
    from satisfactory_mcp.domain.spatial import geo

    map_ts = FRONTEND_SRC / "map" / "map.ts"
    number = r"(-?\d+(?:\.\d+)?)"
    found = re.search(
        rf"MAP_SQUARE_M = \{{ x_min: {number}, x_max: {number}, y_min: {number}, y_max: {number} \}}",
        map_ts.read_text(encoding="utf-8"),
    )
    assert found, "map.ts no longer spells MAP_SQUARE_M as one literal"
    x0, x1, y0, y1 = (float(v) for v in found.groups())
    assert (x0, y0, x1, y1) == geo.MAP_SQUARE_M
