"""CuPy ships no types; this covers what mapgen's CUDA kernels use of it (``mapgen.jit``)."""

from typing import Generic, TypeVar

import numpy as np
from cupy import cuda as cuda
from numpy.typing import NDArray

_Scalar = TypeVar("_Scalar", bound=np.generic)
_Scalar_co = TypeVar("_Scalar_co", bound=np.generic, covariant=True)

class ndarray(Generic[_Scalar_co]):
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def size(self) -> int: ...
    def get(self) -> NDArray[_Scalar_co]: ...
    def copy(self) -> ndarray[_Scalar_co]: ...
    def __getitem__(self, key: slice | tuple[slice, ...], /) -> ndarray[_Scalar_co]: ...

def asarray(a: NDArray[_Scalar], /) -> ndarray[_Scalar]: ...
def empty(shape: int | tuple[int, ...], dtype: type[_Scalar]) -> ndarray[_Scalar]: ...
def full(
    shape: int | tuple[int, ...], fill_value: float, dtype: type[_Scalar]
) -> ndarray[_Scalar]: ...

class RawKernel:
    def __call__(
        self, grid: tuple[int, ...], block: tuple[int, ...], args: tuple[object, ...], /
    ) -> None: ...

class RawModule:
    def __init__(self, *, code: str, options: tuple[str, ...] = ...) -> None: ...
    def get_function(self, name: str) -> RawKernel: ...

class MemoryPool:
    def free_all_blocks(self) -> None: ...
    def set_limit(self, *, size: int) -> None: ...

def get_default_memory_pool() -> MemoryPool: ...
