"""Resource nodes: the static table, its game-version skew, and what the save taps."""

from .extraction import (
    AnnotatedNode,
    MeasuredNode,
    annotate,
    annotate_for_save,
    blocking_buildings,
    can_extract,
    measure_from,
    node_rate,
    occupancy_by_node,
    reachable,
    unresolved_extractors,
    untapped_rate,
)
from .skew import (
    TableSkew,
    drifted_leaf_names,
    identity_notes,
    position_notes,
    skew_for_save,
    skew_from_meta,
    skew_notes,
    table_age,
)
from .table import (
    EXTRACTOR_FOR_KIND,
    GEYSER_CONSUMER,
    SUPPORT_BUILDINGS_FOR_KIND,
    NodeRecord,
    NodeTable,
    load_nodes,
)

__all__ = [
    "EXTRACTOR_FOR_KIND",
    "GEYSER_CONSUMER",
    "SUPPORT_BUILDINGS_FOR_KIND",
    "AnnotatedNode",
    "MeasuredNode",
    "NodeRecord",
    "NodeTable",
    "TableSkew",
    "annotate",
    "annotate_for_save",
    "blocking_buildings",
    "can_extract",
    "drifted_leaf_names",
    "identity_notes",
    "load_nodes",
    "measure_from",
    "node_rate",
    "occupancy_by_node",
    "position_notes",
    "reachable",
    "skew_for_save",
    "skew_from_meta",
    "skew_notes",
    "table_age",
    "unresolved_extractors",
    "untapped_rate",
]
