/* The build writes the page into ../static/, the directory app.py serves at `/`. That output is
 * gitignored, so a fresh clone has no page until `npm ci && npm run build` runs here. emptyOutDir
 * is on, so nothing hand-written may live in static/. The why of each choice, the licence
 * included, is in frontend/README.md. */

import { readFileSync } from "node:fs";

import { defineConfig, type Plugin } from "vite";

// Node's global, declared rather than installing @types/node (see node-fs.d.ts).
declare const process: { env: Record<string, string | undefined> };

// No timestamp or version, so two builds of one source are byte-identical.
const BANNER = [
  "GENERATED by Vite from src/satisfactory_mcp/interfaces/web/frontend/ -- do not edit.",
  "Edit the TypeScript there and run `npm ci && npm run build`; see frontend/README.md.",
  "Bundles Leaflet 1.9.4 (c) 2010-2023 Vladimir Agafonkin, (c) 2010-2011 CloudMade,",
  "BSD-2-Clause -- full text in vendor/LEAFLET-LICENSE beside this file.",
];

// Stamps BANNER into every emitted file after minification; tests/architecture/test_frontend_layout.py asserts BANNER.
function banner(): Plugin {
  return {
    name: "build-banner",
    apply: "build",
    enforce: "post",
    generateBundle(_options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type === "chunk") {
          file.code = `/* ${BANNER.join("\n * ")} */\n${file.code}`;
        } else if (file.fileName.endsWith(".css") && typeof file.source === "string") {
          file.source = `/* ${BANNER.join("\n * ")} */\n${file.source}`;
        }
      }
    },
    transformIndexHtml(html) {
      return `<!--\n  ${BANNER.join("\n  ")}\n-->\n${html}`;
    },
  };
}

// Copies node_modules/leaflet/LICENSE beside the bundle, so every build carries the notice.
function leafletLicence(): Plugin {
  return {
    name: "leaflet-licence",
    apply: "build",
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "vendor/LEAFLET-LICENSE",
        source: readFileSync(new URL("./node_modules/leaflet/LICENSE", import.meta.url), "utf-8"),
      });
    },
  };
}

export default defineConfig({
  // Relative asset URLs, so the page survives being mounted somewhere other than `/`.
  base: "./",
  plugins: [banner(), leafletLicence()],
  build: {
    outDir: "../static",
    emptyOutDir: true,
    // Stable names, no content hash: tests/architecture/test_frontend_layout.py pins static/ by name.
    rollupOptions: {
      output: {
        entryFileNames: "app.js",
        chunkFileNames: "chunk-[name].js",
        assetFileNames: (info) =>
          info.names?.some((n) => n.endsWith(".css")) ? "app.css" : "assets/[name][extname]",
      },
    },
  },
  server: {
    proxy: {
      // /api to a running satisfactory-mcp-web; SSE streams through unbuffered (see README).
      "/api": {
        target: process.env.SATISFACTORY_MCP_WEB || "http://127.0.0.1:8712",
        changeOrigin: true,
        ws: false,
      },
    },
  },
});
