cudaLimitStackSize: int

def getDeviceCount() -> int: ...
def getDevice() -> int: ...
def getDeviceProperties(device: int) -> dict[str, object]: ...
def deviceSetLimit(limit: int, value: int) -> None: ...
